import Foundation

/// Returns localized Unicode block name.
///
/// - Parameter block: The Unicode block name determined in Blocks.txt.
/// - Returns: A localized name.
func localizeBlockName(_ block: String) -> String? {

  switch block {
  case "Adlam": "Adlam"
  case "Aegean Numbers": "Aegean Numbers"
  case "Ahom": "Ahom"
  case "Alchemical Symbols": "Alchemical Symbols"
  case "Alphabetic Presentation Forms": "Alphabetic Presentation Forms"
  case "Anatolian Hieroglyphs": "Anatolian Hieroglyphs"
  case "Ancient Greek Musical Notation": "Ancient Greek Musical Notation"
  case "Ancient Greek Numbers": "Ancient Greek Numbers"
  case "Ancient Symbols": "Ancient Symbols"
  case "Arabic Extended-A": "Arabic Extended-A"
  case "Arabic Extended-B": "Arabic Extended-B"
  case "Arabic Extended-C": "Arabic Extended-C"
  case "Arabic Mathematical Alphabetic Symbols": "Arabic Math Alphabetic Symbols"  // Math -> Mathematical
  case "Arabic Presentation Forms-A": "Arabic Presentation Forms-A"
  case "Arabic Presentation Forms-B": "Arabic Presentation Forms-B"
  case "Arabic Supplement": "Arabic Supplement"
  case "Arabic": "Arabic"
  case "Armenian": "Armenian"
  case "Arrows": "Arrows"
  case "Avestan": "Avestan"
  case "Balinese": "Balinese"
  case "Bamum Supplement": "Bamum Supplement"
  case "Bamum": "Bamum"
  case "Basic Latin": "Basic Latin"
  case "Bassa Vah": "Bassa Vah"
  case "Batak": "Batak"
  case "Bengali": "Bengali"
  case "Beria Erfe": "Beria Erfe"
  case "Bhaiksuki": "Bhaiksuki"
  case "Block Elements": "Block Elements"
  case "Bopomofo Extended": "Bopomofo Extended"
  case "Bopomofo": "Bopomofo"
  case "Box Drawing": "Box Drawing"
  case "Brahmi": "Brahmi"
  case "Braille Patterns": "Braille Patterns"
  case "Buginese": "Buginese"
  case "Buhid": "Buhid"
  case "Byzantine Musical Symbols": "Byzantine Musical Symbols"
  case "Carian": "Carian"
  case "Caucasian Albanian": "Caucasian Albanian"
  case "Chakma": "Chakma"
  case "Cham": "Cham"
  case "Cherokee Supplement": "Cherokee Supplement"
  case "Cherokee": "Cherokee"
  case "Chess Symbols": "Chess Symbols"
  case "Chorasmian": "Chorasmian"
  case "CJK Compatibility Forms": "CJK Compatibility Forms"
  case "CJK Compatibility Ideographs Supplement": "CJK Compatibility Ideographs Supp."
  case "CJK Compatibility Ideographs": "CJK Compatibility Ideographs"
  case "CJK Compatibility": "CJK Compatibility"
  case "CJK Radicals Supplement": "CJK Radicals Supplement"
  case "CJK Strokes": "CJK Strokes"
  case "CJK Symbols and Punctuation": "CJK Symbols and Punctuation"
  case "CJK Unified Ideographs Extension A": "CJK Unified Ideographs Ext. A"  // Extension -> Ext.
  case "CJK Unified Ideographs Extension B": "CJK Unified Ideographs Ext. B"  // Extension -> Ext.
  case "CJK Unified Ideographs Extension C": "CJK Unified Ideographs Ext. C"  // Extension -> Ext.
  case "CJK Unified Ideographs Extension D": "CJK Unified Ideographs Ext. D"  // Extension -> Ext.
  case "CJK Unified Ideographs Extension E": "CJK Unified Ideographs Ext. E"  // Extension -> Ext.
  case "CJK Unified Ideographs Extension F": "CJK Unified Ideographs Ext. F"  // Extension -> Ext.
  case "CJK Unified Ideographs Extension G": "CJK Unified Ideographs Ext. G"  // Extension -> Ext.
  case "CJK Unified Ideographs Extension H": "CJK Unified Ideographs Ext. H"  // Extension -> Ext.
  case "CJK Unified Ideographs Extension I": "CJK Unified Ideographs Ext. I"  // Extension -> Ext.
  case "CJK Unified Ideographs Extension J": "CJK Unified Ideographs Ext. J"  // Extension -> Ext.
  case "CJK Unified Ideographs": "CJK Unified Ideographs"
  case "Combining Diacritical Marks Extended": "Combining Diacritical Marks Extended"
  case "Combining Diacritical Marks for Symbols": "Combining Diacritical Marks for Symbols"
  case "Combining Diacritical Marks Supplement": "Combining Diacritical Marks Supplement"
  case "Combining Diacritical Marks": "Combining Diacritical Marks"
  case "Combining Half Marks": "Combining Half Marks"
  case "Common Indic Number Forms": "Common Indic Number Forms"
  case "Control Pictures": "Control Pictures"
  case "Coptic Epact Numbers": "Coptic Epact Numbers"
  case "Coptic": "Coptic"
  case "Counting Rod Numerals": "Counting Rod Numerals"
  case "Cuneiform Numbers and Punctuation": "Cuneiform Numbers and Punctuation"
  case "Cuneiform": "Cuneiform"
  case "Currency Symbols": "Currency Symbols"
  case "Cypriot Syllabary": "Cypriot Syllabary"
  case "Cypro-Minoan": "Cypro-Minoan"
  case "Cyrillic Extended-A": "Cyrillic Extended-A"
  case "Cyrillic Extended-B": "Cyrillic Extended-B"
  case "Cyrillic Extended-C": "Cyrillic Extended-C"
  case "Cyrillic Extended-D": "Cyrillic Extended-D"
  case "Cyrillic Supplement": "Cyrillic Supplement"
  case "Cyrillic": "Cyrillic"
  case "Deseret": "Deseret"
  case "Devanagari Extended-A": "Devanagari Extended-A"
  case "Devanagari Extended": "Devanagari Extended"
  case "Devanagari": "Devanagari"
  case "Dingbats": "Dingbats"
  case "Dives Akuru": "Dives Akuru"
  case "Dogra": "Dogra"
  case "Domino Tiles": "Domino Tiles"
  case "Duployan": "Duployan"
  case "Early Dynastic Cuneiform": "Early Dynastic Cuneiform"
  case "Egyptian Hieroglyph Format Controls": "Egyptian Hieroglyph Format Controls"
  case "Egyptian Hieroglyphs Extended-A": "Egyptian Hieroglyphs Extended-A"
  case "Egyptian Hieroglyphs": "Egyptian Hieroglyphs"
  case "Elbasan": "Elbasan"
  case "Elymaic": "Elymaic"
  case "Emoticons": "Emoticons"
  case "Enclosed Alphanumeric Supplement": "Enclosed Alphanumeric Supplement"
  case "Enclosed Alphanumerics": "Enclosed Alphanumerics"
  case "Enclosed CJK Letters and Months": "Enclosed CJK Letters and Months"
  case "Enclosed Ideographic Supplement": "Enclosed Ideographic Supplement"
  case "Ethiopic Extended-A": "Ethiopic Extended-A"
  case "Ethiopic Extended-B": "Ethiopic Extended-B"
  case "Ethiopic Extended": "Ethiopic Extended"
  case "Ethiopic Supplement": "Ethiopic Supplement"
  case "Ethiopic": "Ethiopic"
  case "Garay": "Garay"
  case "General Punctuation": "General Punctuation"
  case "Geometric Shapes Extended": "Geometric Shapes Extended"
  case "Geometric Shapes": "Geometric Shapes"
  case "Georgian Extended": "Georgian Extended"
  case "Georgian Supplement": "Georgian Supplement"
  case "Georgian": "Georgian"
  case "Glagolitic Supplement": "Glagolitic Supplement"
  case "Glagolitic": "Glagolitic"
  case "Gothic": "Gothic"
  case "Grantha": "Grantha"
  case "Greek and Coptic": "Greek and Coptic"
  case "Greek Extended": "Greek Extended"
  case "Gujarati": "Gujarati"
  case "Gunjala Gondi": "Gunjala Gondi"
  case "Gurmukhi": "Gurmukhi"
  case "Gurung Khema": "Gurung Khema"
  case "Halfwidth and Fullwidth Forms": "Halfwidth and Fullwidth Forms"
  case "Hangul Compatibility Jamo": "Hangul Compatibility Jamo"
  case "Hangul Jamo Extended-A": "Hangul Jamo Extended-A"
  case "Hangul Jamo Extended-B": "Hangul Jamo Extended-B"
  case "Hangul Jamo": "Hangul Jamo"
  case "Hangul Syllables": "Hangul Syllables"
  case "Hanifi Rohingya": "Hanifi Rohingya"
  case "Hanunoo": "Hanunoo"
  case "Hatran": "Hatran"
  case "Hebrew": "Hebrew"
  case "High Private Use Surrogates": "High Private Use Surrogates"
  case "High Surrogates": "High Surrogates"
  case "Hiragana": "Hiragana"
  case "Ideographic Description Characters": "Ideographic Desc. Characters"
  case "Ideographic Symbols and Punctuation": "Ideographic Symbols and Punctuation"
  case "Imperial Aramaic": "Imperial Aramaic"
  case "Indic Siyaq Numbers": "Indic Siyaq Numbers"
  case "Inscriptional Pahlavi": "Inscriptional Pahlavi"
  case "Inscriptional Parthian": "Inscriptional Parthian"
  case "IPA Extensions": "IPA Extensions"
  case "Javanese": "Javanese"
  case "Kaithi": "Kaithi"
  case "Kaktovik Numerals": "Kaktovik Numerals"
  case "Kana Extended-A": "Kana Extended-A"
  case "Kana Extended-B": "Kana Extended-B"
  case "Kana Supplement": "Kana Supplement"
  case "Kanbun": "Kanbun"
  case "Kangxi Radicals": "Kangxi Radicals"
  case "Kannada": "Kannada"
  case "Katakana Phonetic Extensions": "Katakana Phonetic Extensions"
  case "Katakana": "Katakana"
  case "Kawi": "Kawi"
  case "Kayah Li": "Kayah Li"
  case "Kharoshthi": "Kharoshthi"
  case "Khitan Small Script": "Khitan Small Script"
  case "Khmer Symbols": "Khmer Symbols"
  case "Khmer": "Khmer"
  case "Khojki": "Khojki"
  case "Khudawadi": "Khudawadi"
  case "Kirat Rai": "Kirat Rai"
  case "Lao": "Lao"
  case "Latin Extended Additional": "Latin Extended Additional"
  case "Latin Extended-A": "Latin Extended-A"
  case "Latin Extended-B": "Latin Extended-B"
  case "Latin Extended-C": "Latin Extended-C"
  case "Latin Extended-D": "Latin Extended-D"
  case "Latin Extended-E": "Latin Extended-E"
  case "Latin Extended-F": "Latin Extended-F"
  case "Latin Extended-G": "Latin Extended-G"
  case "Latin-1 Supplement": "Latin-1 Supplement"
  case "Lepcha": "Lepcha"
  case "Letterlike Symbols": "Letterlike Symbols"
  case "Limbu": "Limbu"
  case "Linear A": "Linear A"
  case "Linear B Ideograms": "Linear B Ideograms"
  case "Linear B Syllabary": "Linear B Syllabary"
  case "Lisu Supplement": "Lisu Supplement"
  case "Lisu": "Lisu"
  case "Low Surrogates": "Low Surrogates"
  case "Lycian": "Lycian"
  case "Lydian": "Lydian"
  case "Mahajani": "Mahajani"
  case "Mahjong Tiles": "Mahjong Tiles"
  case "Makasar": "Makasar"
  case "Malayalam": "Malayalam"
  case "Mandaic": "Mandaic"
  case "Manichaean": "Manichaean"
  case "Marchen": "Marchen"
  case "Masaram Gondi": "Masaram Gondi"
  case "Mathematical Alphanumeric Symbols": "Math Alphanumeric Symbols"  // Math -> Mathematical
  case "Mathematical Operators": "Mathematical Operators"
  case "Mayan Numerals": "Mayan Numerals"
  case "Medefaidrin": "Medefaidrin"
  case "Meetei Mayek Extensions": "Meetei Mayek Extensions"
  case "Meetei Mayek": "Meetei Mayek"
  case "Mende Kikakui": "Mende Kikakui"
  case "Meroitic Cursive": "Meroitic Cursive"
  case "Meroitic Hieroglyphs": "Meroitic Hieroglyphs"
  case "Miao": "Miao"
  case "Miscellaneous Mathematical Symbols-A": "Miscellaneous Math Symbols-A"  // Math -> Mathematical
  case "Miscellaneous Mathematical Symbols-B": "Miscellaneous Math Symbols-B"  // Math -> Mathematical
  case "Miscellaneous Symbols and Arrows": "Miscellaneous Symbols and Arrows"
  case "Miscellaneous Symbols and Pictographs": "Miscellaneous Symbols And Pictographs"  // And -> and
  case "Miscellaneous Symbols Supplement": "Miscellaneous Symbols Supplement"
  case "Miscellaneous Symbols": "Miscellaneous Symbols"
  case "Miscellaneous Technical": "Miscellaneous Technical"
  case "Modi": "Modi"
  case "Modifier Tone Letters": "Modifier Tone Letters"
  case "Mongolian Supplement": "Mongolian Supplement"
  case "Mongolian": "Mongolian"
  case "Mro": "Mro"
  case "Multani": "Multani"
  case "Musical Symbols": "Musical Symbols"
  case "Myanmar Extended-A": "Myanmar Extended-A"
  case "Myanmar Extended-B": "Myanmar Extended-B"
  case "Myanmar Extended-C": "Myanmar Extended-C"
  case "Myanmar": "Myanmar"
  case "Nabataean": "Nabataean"
  case "Nag Mundari": "Nag Mundari"
  case "Nandinagari": "Nandinagari"
  case "New Tai Lue": "New Tai Lue"
  case "Newa": "Newa"
  case "NKo": "N'Ko"  // remove ’
  case "Number Forms": "Number Forms"
  case "Nushu": "Nushu"
  case "Nyiakeng Puachue Hmong": "Nyiakeng Puachue Hmong"
  case "Ogham": "Ogham"
  case "Ol Chiki": "Ol Chiki"
  case "Ol Onal": "Ol Onal"
  case "Old Hungarian": "Old Hungarian"
  case "Old Italic": "Old Italic"
  case "Old North Arabian": "Old North Arabian"
  case "Old Permic": "Old Permic"
  case "Old Persian": "Old Persian"
  case "Old Sogdian": "Old Sogdian"
  case "Old South Arabian": "Old South Arabian"
  case "Old Turkic": "Old Turkic"
  case "Old Uyghur": "Old Uyghur"
  case "Optical Character Recognition": "Optical Character Recognition"
  case "Oriya": "Oriya"
  case "Ornamental Dingbats": "Ornamental Dingbats"
  case "Osage": "Osage"
  case "Osmanya": "Osmanya"
  case "Ottoman Siyaq Numbers": "Ottoman Siyaq Numbers"
  case "Pahawh Hmong": "Pahawh Hmong"
  case "Palmyrene": "Palmyrene"
  case "Pau Cin Hau": "Pau Cin Hau"
  case "Phags-pa": "Phags-pa"
  case "Phaistos Disc": "Phaistos Disc"
  case "Phoenician": "Phoenician"
  case "Phonetic Extensions Supplement": "Phonetic Extensions Supplement"
  case "Phonetic Extensions": "Phonetic Extensions"
  case "Playing Cards": "Playing Cards"
  case "Private Use Area": "Private Use Area"
  case "Psalter Pahlavi": "Psalter Pahlavi"
  case "Rejang": "Rejang"
  case "Rumi Numeral Symbols": "Rumi Numeral Symbols"
  case "Runic": "Runic"
  case "Samaritan": "Samaritan"
  case "Saurashtra": "Saurashtra"
  case "Sharada Supplement": "Sharada Supplement"
  case "Sharada": "Sharada"
  case "Shavian": "Shavian"
  case "Shorthand Format Controls": "Shorthand Format Controls"
  case "Sidetic": "Sidetic"
  case "Siddham": "Siddham"
  case "Sinhala Archaic Numbers": "Sinhala Archaic Numbers"
  case "Sinhala": "Sinhala"
  case "Small Form Variants": "Small Form Variants"
  case "Small Kana Extension": "Small Kana Extension"
  case "Sogdian": "Sogdian"
  case "Sora Sompeng": "Sora Sompeng"
  case "Soyombo": "Soyombo"
  case "Spacing Modifier Letters": "Spacing Modifier Letters"
  case "Specials": "Specials"
  case "Sundanese Supplement": "Sundanese Supplement"
  case "Sundanese": "Sundanese"
  case "Sunuwar": "Sunuwar"
  case "Superscripts and Subscripts": "Superscripts and Subscripts"
  case "Supplemental Arrows-A": "Supplemental Arrows-A"
  case "Supplemental Arrows-B": "Supplemental Arrows-B"
  case "Supplemental Arrows-C": "Supplemental Arrows-C"
  case "Supplemental Mathematical Operators": "Supplemental Math Operators"  // Math -> Mathematical
  case "Supplemental Punctuation": "Supplemental Punctuation"
  case "Supplemental Symbols and Pictographs": "Supplemental Symbols and Pictographs"
  case "Supplementary Private Use Area-A": "Supplementary Private Use Area-A"
  case "Supplementary Private Use Area-B": "Supplementary Private Use Area-B"
  case "Sutton SignWriting": "Sutton SignWriting"
  case "Syloti Nagri": "Syloti Nagri"
  case "Symbols and Pictographs Extended-A": "Symbols and Pictographs Extended-A"
  case "Symbols for Legacy Computing Supplement": "Symbols for Legacy Computing Supplement"
  case "Symbols for Legacy Computing": "Symbols for Legacy Computing"
  case "Syriac Supplement": "Syriac Supplement"
  case "Syriac": "Syriac"
  case "Tagalog": "Tagalog"
  case "Tagbanwa": "Tagbanwa"
  case "Tags": "Tags"
  case "Tai Le": "Tai Le"
  case "Tai Tham": "Tai Tham"
  case "Tai Viet": "Tai Viet"
  case "Tai Xuan Jing Symbols": "Tai Xuan Jing Symbols"
  case "Tai Yo": "Tai Yo"
  case "Takri": "Takri"
  case "Tamil Supplement": "Tamil Supplement"
  case "Tamil": "Tamil"
  case "Tangsa": "Tangsa"
  case "Tangut Components": "Tangut Components"
  case "Tangut Components Supplement": "Tangut Components Supplement"
  case "Tangut Supplement": "Tangut Supplement"
  case "Tangut": "Tangut"
  case "Telugu": "Telugu"
  case "Thaana": "Thaana"
  case "Thai": "Thai"
  case "Tibetan": "Tibetan"
  case "Tifinagh": "Tifinagh"
  case "Tirhuta": "Tirhuta"
  case "Todhri": "Todhri"
  case "Tolong Siki": "Tolong Siki"
  case "Toto": "Toto"
  case "Transport and Map Symbols": "Transport And Map Symbols"  // And -> and
  case "Tulu-Tigalari": "Tulu-Tigalari"
  case "Ugaritic": "Ugaritic"
  case "Unified Canadian Aboriginal Syllabics Extended-A":
    "Unified Canadian Aboriginal Syllabics Extended-A"
  case "Unified Canadian Aboriginal Syllabics Extended":
    "Unified Canadian Aboriginal Syllabics Extended"
  case "Unified Canadian Aboriginal Syllabics": "Unified Canadian Aboriginal Syllabics"
  case "Vai": "Vai"
  case "Variation Selectors Supplement": "Variation Selectors Supplement"
  case "Variation Selectors": "Variation Selectors"
  case "Vedic Extensions": "Vedic Extensions"
  case "Vertical Forms": "Vertical Forms"
  case "Vithkuqi": "Vithkuqi"
  case "Wancho": "Wancho"
  case "Warang Citi": "Warang Citi"
  case "Yezidi": "Yezidi"
  case "Yi Radicals": "Yi Radicals"
  case "Yi Syllables": "Yi Syllables"
  case "Yijing Hexagram Symbols": "Yijing Hexagram Symbols"
  case "Zanabazar Square": "Zanabazar Square"
  case "Znamenny Musical Notation": "Znamenny Musical Notation"

  default: nil
  }
}
